#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# This file is part of BridgeDB, a Tor bridge distribution system.
#
# :authors: Isis Lovecruft 0xA3ADB67A2CDB8B35 <isis@torproject.org>
#           please also see AUTHORS file
# :copyright: (c) 2007-2013, The Tor Project, Inc.
#             (c) 2007-2013, all entities within the AUTHORS file
# :license: 3-clause BSD, see included LICENSE for information

from __future__ import print_function

import bridgedb
import os
import sys

from bridgedb import runner
from bridgedb.parse import options


option = options.parseOptions()

if option.subCommand is not None:
    # Hack to set the PYTHONPATH:
    sys.path[:] = map(os.path.abspath, sys.path)
    sys.path.insert(0, os.path.abspath(os.getcwd()))
    sys.path.insert(0, os.path.abspath(os.path.join(os.getcwd(), '../lib')))

    if 'descriptors' in option.subOptions:
        runner.generateDescriptors(option)

    if option.subCommand == 'test':
        if option.subOptions['trial']:
            runner.runTrial(option.subOptions)
        if option.subOptions['unittests']:
            runner.runTests(option.subOptions)
    sys.exit()

# If no suboption was given, just run bridgedb:
else:
    from bridgedb import Main
    Main.run(option)
