#!/usr/bin/env bash

#set -x --

SUDO=
APT_GET=$(which apt-get)
APT_FLAGS='-q --no-install-suggests --no-install-recommends'
PIP=$(which pip)
PIP_FLAGS='--no-use-wheel'
DEPENDS="build-essential openssl sqlite3 python-setuptools"
DEPENDS="${DEPENDS} libgeoip-dev geoip-database libjpeg-dev"
HERE=$(dirname $0)

PYTHON_IMPLEMENTATION=`python -c '
import sys
try:
    import __pypy__
except:
    sys.stdout.write(sys.subversion[0])
else:
    sys.stdout.write("pypy")'`

if [ "$PYTHON_IMPLEMENTATION" == "pypy" ] ; then
    DEPENDS="${DEPENDS} pypy-dev"
else
    DEPENDS="${DEPENDS} python-dev"
fi

if [ "$EUID" != "0" ] ; then SUDO=$(which sudo); fi
# pip is pre-installed on Travis-CI machines in their Python environment, so
# we should avoid reinstalling it (as that might do odd things to the
# virtualenv that we're already inside):
if [ "$TRAVIS" == "true" ] ; then
    DEPENDS="${DEPENDS} realpath"
else
    DEPENDS="${DEPENDS} python-pip"
fi
    
MISSING=""
for dep in $DEPENDS ; do
    if { dpkg -l $dep | grep "ii  $dep" ; } 2>&1 >/dev/null ; then
        printf "" # not missing
    else
        MISSING="${MISSING} $dep"
    fi
done

if test -n "$MISSING" ; then
    printf "Running \"sudo apt-get install %s %s\"...\n" "${APT_FLAGS}" "${MISSING}"
    $SUDO $APT_GET install ${APT_FLAGS} ${MISSING}
fi

# When running on Travis, be sure that environment variables are passed from
# .travis.yml to this script:
if [ "$TRAVIS" == "true" ] ; then
    $PIP install $PIP_FLAGS -r "$HERE/../.travis.requirements.txt"
    $PIP install $PIP_FLAGS "Twisted==$TWISTED_VERSION" "pyOpenSSL==$PYOPENSSL_VERSION"
else
    printf "Running \"pip install %s -r %s\"...\n" "${PIP_FLAGS}" "${HERE}/../requirements.txt"
    $PIP install $PIP_FLAGS -r "$HERE/../requirements.txt"
fi
