#!/usr/bin/env bash

set -x --

THIS_SCRIPT="$(realpath $0)"
HERE="$THIS_SCRIPT"

while [ "${HERE##*/}" != "bridgedb" ] ; do HERE="${HERE%/*}" ; done

THERE="$HERE"
echo "Found top-level repo directory: $THERE"
cd $THERE

mkdir run
cp -R -t run bridgedb.conf captchas .gnupg
# Add '127.0.0.1' to EMAIL_DOMAINS in bridgedb.conf. This should ONLY be
# done on testing servers, never on production servers.
sed -r -i -e "s/(EMAIL_DOMAINS)(.*)(])/\1\2\, '127.0.0.1']/" run/bridgedb.conf
# Change EMAIL_SMTP_PORT to 2525:
sed -r -i -e "s/(EMAIL_SMTP_PORT = )([1-9]{2,5})/\12525/" run/bridgedb.conf
# Enable plaintext HTTP distribution, otherwise the mechanize-based tests in
# test_https.py will fail with CERTIFICATE_VERIFY_FAILED because urllib2
# won't recognize our self-signed certificate:
sed -r -i -e "s/(HTTP_UNENCRYPTED_BIND_IP = )(None)/\1'127.0.0.1'/" run/bridgedb.conf
sed -r -i -e "s/(HTTP_UNENCRYPTED_PORT = )(None)/\16788/" run/bridgedb.conf
sed -r -i -e "s/(SERVER_PUBLIC_FQDN = )(.*)/\1'127.0.0.1:6788'/" run/bridgedb.conf
leekspin -n 100
cp -t run networkstatus-bridges cached-extrainfo* bridge-descriptors
./scripts/make-ssl-cert
cp -t run privkey.pem cert
